# Generated by Django 5.0.4 on 2025-03-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0003_shell'),
    ]

    operations = [
        migrations.AddField(
            model_name='shell',
            name='video_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
