# Generated by Django 5.0.4 on 2025-03-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0005_shell_pdf_file_shell_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='shell',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
