# Generated by Django 5.0.4 on 2025-03-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0006_shell_cloudinary_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shell',
            name='lecture_type',
            field=models.CharField(choices=[('demo', 'Demo Lecture'), ('paid', 'Paid Lecture')], default='paid', max_length=10),
        ),
    ]
