# Generated by Django 5.0.4 on 2025-03-07 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0008_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='course_content/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='Teacher.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
