# Generated by Django 5.0.4 on 2025-03-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='completed_lectures',
            field=models.TextField(default=''),
        ),
    ]
